/**
 * Workday Activity Tracker API
 * API for managing work tasks and generating reports.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BlockReason { 
    reason: string;
    resolution?: string | null;
    resolvedAt?: string | null;
}

