/**
 * Workday Activity Tracker API
 * API for managing work tasks and generating reports.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Task { 
    id?: number;
    description: string;
    status: Task.StatusEnum;
    createdAt: string;
    scheduledStart?: string | null;
    parentTaskId?: number | null;
    /**
     * Total active time in seconds
     */
    activeTime?: number;
    /**
     * Total elapsed time in seconds since creation
     */
    elapsedTime?: number;
}
export namespace Task {
    export type StatusEnum = 'TO_DO' | 'SCHEDULED' | 'IN_PROGRESS' | 'PENDING' | 'BLOCKED' | 'COMPLETED';
    export const StatusEnum = {
        ToDo: 'TO_DO' as StatusEnum,
        Scheduled: 'SCHEDULED' as StatusEnum,
        InProgress: 'IN_PROGRESS' as StatusEnum,
        Pending: 'PENDING' as StatusEnum,
        Blocked: 'BLOCKED' as StatusEnum,
        Completed: 'COMPLETED' as StatusEnum
    };
}


