/**
 * Workday Activity Tracker API
 * API for managing work tasks and generating reports.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TasksIdResolvePutRequest { 
    resolution: string;
    nextStatus: TasksIdResolvePutRequest.NextStatusEnum;
}
export namespace TasksIdResolvePutRequest {
    export type NextStatusEnum = 'PENDING' | 'COMPLETED';
    export const NextStatusEnum = {
        Pending: 'PENDING' as NextStatusEnum,
        Completed: 'COMPLETED' as NextStatusEnum
    };
}


